GET http://localhost:3000/usuarios


###

PUT http://localhost:3000/usuarios/Blanka
Content-Type: application/json

{
    "id": 5,
    "nombre": "Blanka",
    "edad": 25,
    "lugarProcedencia": "Spain"
}

###
DELETE http://localhost:3000/usuarios/2
